using UnityEngine;
using System.Collections;

public class Problem2 : MonoBehaviour
{
    /*
            Each new term in the Fibonacci sequence is generated by adding the previous two terms.
            By starting with 1 and 2, the first 10 terms will be:

            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

            By considering the terms in the Fibonacci sequence whose values do not exceed four million,
            find the sum of the even-valued terms.
    */

    // Use this for initialization
    void Start ()
    {
        long first = 1;
        long second = 1;
        long newNum = 0;

        //newNum = first + second; // 3
        long sum = 0;
        while(newNum < 4000000)
        {
            if(newNum % 2 == 0)
            {
                print(newNum + " is even!");
                sum += newNum;
            }
            first = second;
            second = newNum;

            newNum = first + second;
        }

        print("Solution to Problem 2: " + sum);
	}
	
	// Update is called once per frame
	void Update ()
    {
	
	}
}
